### ISSUE TITLE
The Same Issue Raised in React Repository , The Title of Blog Page is named as Stretchhhhh .

### ISSUE THREAD

**Issue by hrishikeshp7** [covid19india/blog#5]
The title of the Blog page is named as Stretchhhhh . 
I have got it fixed in my forked repository please allow me to Contribute in this project

**Comment by hrishikeshp7** [comment]
I have fixed it just let me know when contribution is available , 
you can see what i changed at https://github.com/hrishikeshp7/Covid-19-India-Fixing-heading-Error

**Comment by hrishikeshp7** [comment]
I have changed the _config.yml files

**Comment by bee-rickey** [comment]
It's an intentional blog title :)
